version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=postgres
      - REDIS_HOST=redis
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
      - processed:/app/processed
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-network

  celery_worker:
    build: ./backend
    command: celery -A app.worker worker --loglevel=info
    environment:
      - POSTGRES_SERVER=postgres
      - REDIS_HOST=redis
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
      - processed:/app/processed
    depends_on:
      - backend
      - redis
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  uploads:
  processed:

networks:
  app-network:
    driver: bridge 